### ISSUE TITLE
No validation found for invalid card details

### ISSUE THREAD

**Issue by tijopromantia** [hps/heartland-prestashop-plugin#17]
Hi,
When I tested the module, there is no validation for expiry date. It is completing payment when I had given invalid details( in test mode)

**Comment by slogsdon** [comment]
HI @tijopromantia!

Our test environment does not reach out to the issuing banks, so there will not be any card verification completed like it would in production. If you want to test these error cases, please download the list of hardcoded values from this page: https://developer.heartlandpaymentsystems.com/Documentation/v2/testing-and-certification/. There will be specific dollar amounts to use during your transactions to evoke specific error codes. Password for the spreadsheet is `heartland`.
